// <auto-generated />
using FF14BOM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FF14BOM.Migrations
{
    [DbContext(typeof(WebContext))]
    [Migration("20260421141122_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FF14BOM.Models.BOM", b =>
                {
                    b.Property<string>("Pro_Id")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Mtr_id")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("Use_QTY")
                        .HasColumnType("int");

                    b.HasKey("Pro_Id", "Mtr_id");

                    b.ToTable("BOM");
                });

            modelBuilder.Entity("FF14BOM.Models.Item", b =>
                {
                    b.Property<string>("Mtr_id")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Mtr_Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Mtr_type")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<bool>("NPC_Sell")
                        .HasColumnType("bit");

                    b.HasKey("Mtr_id");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("FF14BOM.Models.MaterialType", b =>
                {
                    b.Property<string>("Mtr_type")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Mtr_Type_name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Mtr_type");

                    b.ToTable("MaterialType");
                });

            modelBuilder.Entity("FF14BOM.Models.Product", b =>
                {
                    b.Property<string>("Pro_Id")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Pro_Level")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Pro_Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Pro_Type")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Pro_part")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Pro_Id");

                    b.ToTable("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
